### PR TITLE
Add PROXY_PATH

### LINKED ISSUE #5: can't be access when it mounted on a subfolder behind nginx
can't be access when it mounted on a subfolder behind nginx

for example:
this site is on `http://localhost/a/b/c/bull-board`. the path `/a/b/c` is nginx `proxy_pass` and `bull-board` is container. in the container, all pages are on `/`, but it will make browser to redirect to `http://localhost/`

https://github.com/felixmosh/bull-board/blob/master/README.md#hosting-router-on-a-sub-path

### PR DESCRIPTION
**Pull request by Diluka**
close #5

### CODE REVIEW

**Comment by Deadly0** [comment]
@Diluka hi, what the difference between BASE_PATH and PROXY_PATH?

**Comment by Diluka** [comment]
> @Diluka hi, what the difference between BASE_PATH and PROXY_PATH?

BASE_PATH is internal path for express server, PROXY_PATH is external path for nginx https://github.com/felixmosh/bull-board#hosting-router-on-a-sub-path

the page is SPA. so it has a base href as source link prefix https://github.com/felixmosh/bull-board/blob/master/src/ui/index.ejs#L9. PROXY_PATH tells the page how to add the link prefix.

**Comment by Diluka** [comment]
Added REDIS_DB config @Deadly0

**Comment by patrixr** [comment]
@Deadly0 @Diluka Would love to see `REDIS_DB` released, was looking to add that myself 👍

**Comment by Diluka** [comment]
@Deadly0 could you review please?

**Comment by Deadly0** [comment]
@Diluka I will review soon

**Comment by Diluka** [comment]
@Deadly0 is there any problem?

**Comment by vishalvijay** [comment]
@Deadly0 Waiting for `REDIS_DB` to get released

**Comment by Deadly0** [comment]
@Diluka sorry for delay, i'll release today

**Pull request merged**
